import { useEffect,useMemo,useState,type ChangeEvent } from 'react';
import { Check,ChevronLeft,ChevronRight,Copy,ExternalLink,ImagePlus,Plus,Share2,Trash2 } from 'lucide-react';
import { api,supabase } from '../lib/api';

type Service={id?:string;name:string;duration_minutes:number;price_cents:number;active:boolean};
type Snapshot={progress:{current_step:number;completed_steps:number[];draft:Record<string,unknown>}|null;shop:{id:string;name:string;slug:string;onboarding_completed:boolean;onboarding_step:number;whatsapp:string|null;instagram:string|null;address:string|null;theme_mode:'light'|'dark';palette_key:string;custom_accent:string|null;logo_asset_path:string|null;cover_asset_path:string|null;background_asset_path:string|null};services:Service[];hours:{weekday:number;opens_at:string;closes_at:string}[];amenities:string[];palettes:Palette[];owner:{display_name:string;phone?:string|null}};
type Palette={palette_key:string;label:string;light_background:string;light_surface:string;light_text:string;light_text_muted:string;light_accent:string;dark_background:string;dark_surface:string;dark_text:string;dark_text_muted:string;dark_accent:string};
type Props={onDone:()=>void;shopId?:string};
const amenityOptions=[['wifi','Wi-Fi'],['parking','Estacionamento'],['accessibility','Acessibilidade'],['kids','Atende crianças'],['air-conditioning','Ar-condicionado']];
const weekdays=[['1','SEG'],['2','TER'],['3','QUA'],['4','QUI'],['5','SEX'],['6','SÁB'],['0','DOM']];
const suggestions=[['Corte',30,3500],['Barba',30,2500],['Corte + Barba',60,5500]] as const;
const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);

export function OwnerOnboarding({onDone,shopId:initialShopId}:Props){
 const [shopId,setShopId]=useState(initialShopId??''),[step,setStep]=useState(1),[completed,setCompleted]=useState<number[]>([]),[draft,setDraft]=useState<Record<string,unknown>>({}),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(Boolean(initialShopId)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);
 const [name,setName]=useState(''),[slug,setSlug]=useState(''),[displayName,setDisplayName]=useState(''),[whatsapp,setWhatsapp]=useState(''),[instagram,setInstagram]=useState(''),[address,setAddress]=useState(''),[amenities,setAmenities]=useState<string[]>([]),[services,setServices]=useState<Service[]>([]),[weekdaysSelected,setWeekdaysSelected]=useState<number[]>([1,2,3,4,5,6]),[opensAt,setOpensAt]=useState('09:00'),[closesAt,setClosesAt]=useState('19:00'),[breakEnabled,setBreakEnabled]=useState(false),[breakStart,setBreakStart]=useState('12:00'),[breakEnd,setBreakEnd]=useState('13:00'),[paletteKey,setPaletteKey]=useState('fio-black'),[themeMode,setThemeMode]=useState<'light'|'dark'>('dark'),[customAccent,setCustomAccent]=useState('#ffffff'),[logoPath,setLogoPath]=useState<string|null>(null),[coverPath,setCoverPath]=useState<string|null>(null),[backgroundPath,setBackgroundPath]=useState<string|null>(null);
 const publicLink=shopId&&slug?`${window.location.origin}/b/${slug}`:'';
 useEffect(()=>{if(!shopId)return;let active=true;setLoading(true);api<Snapshot>('/onboarding/progress',shopId).then(s=>{if(!active)return;setSnapshot(s);const d=s.progress?.draft??{};setStep(s.progress?.current_step??s.shop.onboarding_step??1);setCompleted(s.progress?.completed_steps??[]);setDraft(d);setName(s.shop.name);setSlug(s.shop.slug);setWhatsapp(s.shop.whatsapp??s.owner.phone??'');setInstagram(s.shop.instagram??'');setAddress(s.shop.address??'');setAmenities(s.amenities);setServices(s.services);setWeekdaysSelected(s.hours.map(h=>h.weekday));if(s.hours[0]){setOpensAt(s.hours[0].opens_at.slice(0,5));setClosesAt(s.hours[0].closes_at.slice(0,5));}setPaletteKey(s.shop.palette_key);setThemeMode(s.shop.theme_mode);setCustomAccent(s.shop.custom_accent??'#ffffff');setLogoPath(s.shop.logo_asset_path);setCoverPath(s.shop.cover_asset_path);setBackgroundPath(s.shop.background_asset_path);setLoading(false);}).catch(e=>{if(active){setError((e as Error).message);setLoading(false);}});return()=>{active=false;};},[shopId]);
 const palettes=snapshot?.palettes??[];const selectedPalette=palettes.find(p=>p.palette_key===paletteKey);
 const previewStyle=useMemo(()=>{const p=selectedPalette;const dark=themeMode==='dark';return {'--ob-bg':customAccent&&paletteKey==='custom'?(dark?'#101010':'#f7f7f4'):(dark?p?.dark_background??'#080808':p?.light_background??'#f5f5f2'),'--ob-surface':dark?p?.dark_surface??'#111':p?.light_surface??'#fff','--ob-text':dark?p?.dark_text??'#fff':p?.light_text??'#111','--ob-muted':dark?p?.dark_text_muted??'#999':p?.light_text_muted??'#666','--ob-accent':paletteKey==='custom'?customAccent:(dark?p?.dark_accent??'#fff':p?.light_accent??'#111')} as React.CSSProperties;},[selectedPalette,paletteKey,themeMode,customAccent]);
 const setStepDraft=async(next:number,extra:Record<string,unknown>={})=>{if(!shopId)return;setBusy(true);setError('');try{const nextCompleted=Array.from(new Set([...completed,step])).sort();await api('/onboarding/setup',shopId,{setup:{name,slug,whatsapp,instagram,address,themeMode,paletteKey,customAccent:paletteKey==='custom'?customAccent:null,amenities,logoAssetPath:logoPath,coverAssetPath:coverPath,backgroundAssetPath:backgroundPath},step:next,completedSteps:nextCompleted,draft:{...draft,...extra}});setCompleted(nextCompleted);setDraft(d=>({...d,...extra}));setStep(next);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const createFirst=async()=>{setBusy(true);setError('');try{const r=await api<{barbershopId:string}>('/onboarding',undefined,{mode:'create',name,slug,displayName});setShopId(r.barbershopId);sessionStorage.setItem('fio-shop',r.barbershopId);return r.barbershopId;}catch(e){setError((e as Error).message);return '';}finally{setBusy(false);}};
 const continueFromFirst=async()=>{if(!shopId){const id=await createFirst();if(!id)return;setBusy(true);try{await api('/onboarding/setup',id,{setup:{name,slug,whatsapp,instagram,address,themeMode,paletteKey,customAccent:paletteKey==='custom'?customAccent:null,amenities},step:2,completedSteps:[1],draft:{} });setCompleted([1]);setStep(2);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}else await setStepDraft(2);};
 const saveService=async(s:Service)=>{if(!shopId)return;setBusy(true);setError('');try{const r=await api<Service>('/onboarding/services',shopId,{id:s.id,name:s.name,durationMinutes:s.duration_minutes,priceCents:s.price_cents,active:s.active});setServices(list=>s.id?list.map(x=>x.id===s.id?r:{...x}):[...list,r]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const upload=async(e:ChangeEvent<HTMLInputElement>,kind:'logo'|'cover'|'background')=>{const file=e.target.files?.[0];if(!file||!shopId||!supabase)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Use JPG, PNG ou WebP de até 5 MB.');return;}setBusy(true);setError('');try{const path=`${shopId}/${(await supabase.auth.getUser()).data.user?.id}/${kind}-${Date.now()}.${file.type.split('/')[1].replace('jpeg','jpg')}`;const r=await supabase.storage.from('branding-assets').upload(path,file,{upsert:true,contentType:file.type});if(r.error)throw r.error;kind==='logo'?setLogoPath(path):kind==='cover'?setCoverPath(path):setBackgroundPath(path);}catch(e){setError((e as Error).message||'Não foi possível enviar a imagem.');}finally{setBusy(false);}};
 const activate=async()=>{if(!shopId)return;setBusy(true);setError('');try{await api('/onboarding/activate',shopId,{});setSuccess(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const copy=async()=>{if(publicLink)await navigator.clipboard?.writeText(publicLink);};const share=async()=>{if(publicLink&&navigator.share)await navigator.share({title:name,text:`Agora você pode agendar seu horário comigo pelo link: ${publicLink}`,url:publicLink});else await copy();};
 if(loading)return <div className="owner-onboarding ob-loading">Carregando seu progresso…</div>;
 if(success)return <div className="owner-onboarding ob-success"><span className="ob-success-mark"><Check/></span><p className="eyebrow">TUDO PRONTO</p><h1>Sua barbearia está pronta.</h1><p className="ob-muted">O espaço já está disponível para seus clientes.</p><div className="ob-success-actions"><a href={`/b/${slug}`} target="_blank" rel="noreferrer"><ExternalLink size={16}/>Ver página do cliente</a><button onClick={()=>void copy()}><Copy size={16}/>Copiar link</button><button onClick={()=>void share()}><Share2 size={16}/>Compartilhar</button><button onClick={onDone}>Instalar FIO Gestão</button></div><div className="ob-qr"><img src={`https://quickchart.io/qr?size=180&text=${encodeURIComponent(publicLink)}`} alt="QR Code da página pública"/><a download="fio-link.png" href={`https://quickchart.io/qr?size=800&text=${encodeURIComponent(publicLink)}`}>Baixar QR Code</a></div><small className="ob-muted">A instalação do app pode ser feita pelo menu do navegador.</small></div>;
 if(!shopId&&step!==1)return null;
 const canContinue=step===1?Boolean(name.trim().length>=2&&slug.match(/^[a-z0-9-]{3,60}$/)&&whatsapp.trim().length>=8&&displayName.trim().length>=2):step===2?services.some(s=>s.active):step===3?weekdaysSelected.length>0&&opensAt<closesAt:step===4?Boolean(paletteKey):true;
 return <main className="owner-onboarding" style={previewStyle}>
  <header className="ob-header"><span className="ob-wordmark">fio<sup>®</sup></span><button className="ob-exit" onClick={()=>void supabase?.auth.signOut()}>Sair</button></header>
  <section className="ob-progress"><div><span>Passo {step} de 5</span><strong>{['Sua barbearia','Serviços','Equipe e horários','Identidade','Revisar'][step-1]}</strong></div><div className="ob-progress-track"><i style={{width:`${step/5*100}%`}}/></div></section>
  <section className="ob-content">
   {step===1&&<><p className="ob-eyebrow">SUA BARBEARIA</p><h1>Qual é o nome do seu espaço?</h1><p className="ob-muted">Começamos pelo essencial. Você pode ajustar o restante depois.</p><label>Nome da barbearia<input autoFocus value={name} maxLength={100} placeholder="Barbearia Oliveira" onChange={e=>{setName(e.target.value);if(!shopId)setSlug(slugify(e.target.value));}}/></label><label>WhatsApp<input value={whatsapp} inputMode="tel" type="tel" placeholder="(11) 99999-9999" onChange={e=>setWhatsapp(e.target.value)}/></label><label>Instagram <small>opcional</small><input value={instagram} placeholder="@sua_barbearia" onChange={e=>setInstagram(e.target.value)}/></label><label>Endereço <small>opcional</small><input value={address} placeholder="Rua, número e bairro" onChange={e=>setAddress(e.target.value)}/></label><label>Link público<input className="ob-slug" value={`/b/${slug||'sua-barbearia'}`} onChange={e=>setSlug(slugify(e.target.value.replace('/b/','')))} /></label><div className="ob-amenities"><span>Comodidades <small>opcional</small></span><div>{amenityOptions.map(([key,label])=><button type="button" className={amenities.includes(key)?'selected':''} key={key} onClick={()=>setAmenities(a=>a.includes(key)?a.filter(x=>x!==key):[...a,key])}>{amenities.includes(key)?<Check size={14}/>:null}{label}</button>)}</div></div></>}
   {step===2&&<><p className="ob-eyebrow">SERVIÇOS</p><h1>O que você oferece?</h1><p className="ob-muted">Comece com uma sugestão e ajuste preço e duração.</p><div className="ob-suggestions">{suggestions.map(([label,duration,price])=><button type="button" key={label} disabled={services.some(s=>s.name.toLowerCase()===label.toLowerCase())} onClick={()=>void saveService({name:label,duration_minutes:duration,price_cents:price,active:true})}><span>{label}<small>{duration} min · {money(price)}</small></span><Plus size={17}/></button>)}</div><div className="ob-list">{services.map(s=><div key={s.id??s.name}><input aria-label={`Nome ${s.name}`} value={s.name} onChange={e=>setServices(xs=>xs.map(x=>x===s?{...x,name:e.target.value}:x))}/><input aria-label={`Duração ${s.name}`} type="number" min="10" max="240" step="5" value={s.duration_minutes} onChange={e=>setServices(xs=>xs.map(x=>x===s?{...x,duration_minutes:Number(e.target.value)}:x))}/><input aria-label={`Preço ${s.name}`} type="number" min="0" step="0.01" value={(s.price_cents/100).toFixed(2)} onChange={e=>setServices(xs=>xs.map(x=>x===s?{...x,price_cents:Math.round(Number(e.target.value)*100)}:x))}/><button type="button" aria-label={`Desativar ${s.name}`} onClick={()=>void saveService({...s,active:!s.active})} className={s.active?'ob-active':'ob-inactive'}>{s.active?'Ativo':'Inativo'}</button><button type="button" aria-label={`Salvar ${s.name}`} onClick={()=>void saveService(s)}><Check size={16}/></button><button type="button" aria-label={`Remover ${s.name}`} onClick={()=>setServices(xs=>xs.filter(x=>x!==s))}><Trash2 size={16}/></button></div>)}</div><button type="button" className="ob-add" onClick={()=>setServices(xs=>[...xs,{name:'Novo serviço',duration_minutes:30,price_cents:0,active:true}])}><Plus size={16}/>Adicionar serviço</button></>}
   {step===3&&<><p className="ob-eyebrow">EQUIPE E HORÁRIOS</p><h1>Quando você atende?</h1><p className="ob-muted">Um horário padrão para começar. Você poderá detalhar depois.</p><div className="ob-owner"><span className="ob-avatar">{(displayName||snapshot?.owner.display_name||'Você').split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{displayName||snapshot?.owner.display_name||'Você'}</strong><small>Responsável</small></div></div><div className="ob-weekdays">{weekdays.map(([value,label])=><button type="button" className={weekdaysSelected.includes(Number(value))?'selected':''} key={value} onClick={()=>setWeekdaysSelected(xs=>xs.includes(Number(value))?xs.filter(x=>x!==Number(value)):[...xs,Number(value)])}>{label}</button>)}</div><div className="ob-time-grid"><label>Abre às<input type="time" value={opensAt} onChange={e=>setOpensAt(e.target.value)}/></label><label>Fecha às<input type="time" value={closesAt} onChange={e=>setClosesAt(e.target.value)}/></label></div><label className="ob-check"><input type="checkbox" checked={breakEnabled} onChange={e=>setBreakEnabled(e.target.checked)}/>Intervalo</label>{breakEnabled&&<div className="ob-time-grid"><label>Início intervalo<input type="time" value={breakStart} onChange={e=>setBreakStart(e.target.value)}/></label><label>Fim intervalo<input type="time" value={breakEnd} onChange={e=>setBreakEnd(e.target.value)}/></label></div>}<p className="ob-muted ob-small">Adicionar profissionais convidados fica disponível no FIO Gestão. O responsável já aparece como profissional.</p></>}
   {step===4&&<><p className="ob-eyebrow">IDENTIDADE</p><h1>Como seus clientes vão ver o FIO?</h1><p className="ob-muted">Escolha um sistema visual. Tudo pode ser trocado depois.</p><div className="ob-palette-grid">{palettes.map(p=><button type="button" className={paletteKey===p.palette_key?'selected':''} key={p.palette_key} onClick={()=>setPaletteKey(p.palette_key)} style={{'--swatch':themeMode==='dark'?p.dark_accent:p.light_accent} as React.CSSProperties}><i/><span>{p.label}</span></button>)}<button type="button" className={paletteKey==='custom'?'selected':''} onClick={()=>setPaletteKey('custom')}><i style={{background:customAccent}}/><span>Personalizado</span></button></div>{paletteKey==='custom'&&<label>Cor principal<input type="color" value={customAccent} onChange={e=>setCustomAccent(e.target.value)}/></label>}<div className="ob-theme"><button type="button" className={themeMode==='dark'?'selected':''} onClick={()=>setThemeMode('dark')}>Escuro</button><button type="button" className={themeMode==='light'?'selected':''} onClick={()=>setThemeMode('light')}>Claro</button></div><div className="ob-upload-grid"><label><span><ImagePlus size={17}/>Logo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e,'logo')}/>{logoPath&&<small>Enviada</small>}</label><label><span><ImagePlus size={17}/>Capa</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e,'cover')}/>{coverPath&&<small>Enviada</small>}</label><label><span><ImagePlus size={17}/>Fundo <small>opcional</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e,'background')}/>{backgroundPath&&<small>Enviada</small>}</label></div><div className="ob-preview" style={{backgroundImage:coverPath?undefined:undefined}}><div className="ob-preview-logo">{logoPath?<ImagePlus size={18}/>:<span>LOGO</span>}</div><div><strong>{name||'Sua barbearia'}</strong><small>Corte · {services.find(s=>s.active)?.price_cents?money(services.find(s=>s.active)!.price_cents):'R$ 35,00'}</small></div><button type="button" style={{background:'var(--ob-accent)'}}>Agendar</button></div></>}
   {step===5&&<><p className="ob-eyebrow">REVISAR</p><h1>Tudo pronto.</h1><p className="ob-muted">Confira o essencial antes de ativar sua barbearia.</p><div className="ob-review"><div><strong>{name}</strong><span>{services.filter(s=>s.active).length} serviços · {weekdaysSelected.length?weekdaysSelected.map(d=>weekdays.find(x=>Number(x[0])===d)?.[1]).join(' · '):'Nenhum dia'}</span><span>{opensAt}–{closesAt}</span><span>{whatsapp?'WhatsApp configurado':'WhatsApp pendente'}</span></div><div className="ob-review-preview" style={previewStyle}><strong>{name||'Sua barbearia'}</strong><small>{selectedPalette?.label??'Personalizado'} · tema {themeMode==='dark'?'escuro':'claro'}</small></div></div></>}
   {error&&<p className="ob-error" role="alert">{error}</p>}
  </section>
  <footer className="ob-footer"><button type="button" className="ob-secondary" disabled={step===1||busy} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={17}/>Voltar</button>{step<5?<button type="button" className="ob-primary" disabled={!canContinue||busy} onClick={async()=>{if(step===1&&!shopId){await continueFromFirst();}else if(step===3){await setStepDraft(4);await api('/onboarding/hours',shopId,{weekdays:weekdaysSelected,opensAt,closesAt,breakStart:breakEnabled?breakStart:null,breakEnd:breakEnabled?breakEnd:null},'POST');}else await setStepDraft(step+1);}}>{busy?'Salvando…':'Continuar'}<ChevronRight size={17}/></button>:<button type="button" className="ob-primary" disabled={!canContinue||busy} onClick={()=>void activate()}>{busy?'Ativando…':'Ativar minha barbearia'}<Check size={17}/></button>}</footer>
 </main>;
}
