import { useEffect,useRef,useState,type FormEvent,type ReactNode } from 'react';
import { ArrowUp, Plus, Sparkles, History, WifiOff, LockKeyhole, TriangleAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api,RequestError } from '../lib/api';
import { suggestions,type Role,type Plan } from '../../shared/domain';
import { Modal } from './ui';
interface Message { id:string;role:'user'|'assistant';content:string }
function InlineMarkdown({text}:{text:string}){
 const parts:ReactNode[]=[];const re=/(\*\*[^*\n]+\*\*|`[^`\n]+`)/g;let last=0,m:RegExpExecArray|null,i=0;
 while((m=re.exec(text))){if(m.index>last)parts.push(text.slice(last,m.index));const t=m[0];parts.push(t.startsWith('**')?<strong key={i++}>{t.slice(2,-2)}</strong>:<code key={i++}>{t.slice(1,-1)}</code>);last=m.index+t.length;}if(last<text.length)parts.push(text.slice(last));return <>{parts}</>;
}
function SafeMarkdown({text}:{text:string}){return <div className="fio-markdown">{text.split(/\n{2,}/).map((b,i)=><p key={i}>{b.split('\n').map((l,j,a)=><span key={j}><InlineMarkdown text={l}/>{j<a.length-1&&<br/>}</span>)}</p>)}</div>;}

export function AssistantMessage({message}:{message:Message}){return <article className={`message ${message.role}`}><span className="message-author">{message.role==='assistant'?<><Sparkles size={15}/> FIO IA</>:'Você'}</span><div>{message.role==='assistant'?<SafeMarkdown text={message.content}/>:message.content}</div></article>;}
export function AssistantSuggestions({role,onSelect}:{role:Role;onSelect:(text:string)=>void}){return <div className="suggestions">{suggestions[role].map(s=><button key={s} onClick={()=>onSelect(s)}>{s}<ArrowUp size={16}/></button>)}</div>;}
export function AssistantEmptyState({role,onSelect}:{role:Role;onSelect:(text:string)=>void}){const description=role==='OWNER'?'Posso ajudar você a organizar sua barbearia e encontrar informações do negócio.':role==='BARBER'?'Posso ajudar com sua rotina, agenda e informações da barbearia.':'Posso ajudar com seus horários, agendamentos e dúvidas sobre a barbearia.';return <div className="assistant-empty"><div className="ai-symbol"><Sparkles size={20} strokeWidth={1.5}/></div><div className="assistant-empty-copy"><strong>Olá! Eu sou o Assistente FIO.</strong><p className="muted">{description}</p><AssistantSuggestions role={role} onSelect={onSelect}/></div></div>;}
export function AssistantErrorState({error,onRetry}:{error:RequestError;onRetry?:()=>void}){const Icon=error.code==='OFFLINE'?WifiOff:error.code==='PLAN_REQUIRED'?LockKeyhole:TriangleAlert;return <div className="notice" role="alert"><Icon size={18}/><span>{error.message}</span>{onRetry&&<button type="button" className="notice-retry" onClick={onRetry}>Tentar de novo</button>}</div>;}
export function AssistantComposer({value,onChange,onSubmit,busy}:{value:string;onChange:(v:string)=>void;onSubmit:(e:FormEvent)=>void;busy:boolean}){return <form className="composer" onSubmit={onSubmit}><textarea aria-label="Mensagem para o Assistente" placeholder="Pergunte ao FIO…" maxLength={2000} rows={1} value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(value.trim()&&!busy)onSubmit(e);}}}/><button className="send-button" aria-label="Enviar mensagem" disabled={!value.trim()||busy}><ArrowUp size={20}/></button></form>;}
export function AssistantChat({role,plan,aiEnabled,shopId,demo,base}:{role:Role;plan:Plan;aiEnabled:boolean;shopId:string;demo:boolean;base:string}) {
 const [messages,setMessages]=useState<Message[]>([]),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<RequestError|null>(null),[conversationId,setConversationId]=useState<string>(),[history,setHistory]=useState<{id:string;title:string}[]|null>(null),[failedText,setFailedText]=useState<string>();
 const end=useRef<HTMLDivElement>(null),navigate=useNavigate();
 useEffect(()=>{end.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'end'});},[messages,busy]);
 async function send(text:string){if(!text.trim()||busy)return;setError(null);setFailedText(undefined);
  if(demo){setError(new RequestError('AI_UNAVAILABLE','Esta é uma demonstração. Conecte o Supabase e um provedor de IA para conversar com dados reais.'));return;}
  if(!aiEnabled){setError(new RequestError('PLAN_REQUIRED','O Assistente está disponível a partir do plano PRO.'));return;}
  const message=text.trim();setBusy(true);setMessages(prev=>[...prev,{id:crypto.randomUUID(),role:'user',content:message}]);setValue('');
  try{const result=await api<{conversationId:string;message:string}>('/assistant',shopId,{message,...(conversationId?{conversationId}:{})});setConversationId(result.conversationId);setMessages(prev=>[...prev,{id:crypto.randomUUID(),role:'assistant',content:result.message}]);}
  catch(e){setFailedText(message);setError(e instanceof RequestError?e:new RequestError('ERROR','Não foi possível responder.'));}finally{setBusy(false);}
 }
 async function submit(e:FormEvent){e.preventDefault();await send(value);}
 async function showHistory(){if(demo){setHistory([]);return;}try{setHistory(await api('/conversations',shopId));}catch(e){setError(e as RequestError);}}
 async function openConversation(id:string){try{setMessages(await api(`/conversations/${id}`,shopId));setConversationId(id);setHistory(null);setError(null);}catch(e){setError(e as RequestError);}}
 return <div className="assistant-page assistant-chat-screen"><div className="assistant-toolbar"><div className="assistant-toolbar-title"><div><strong>Assistente FIO</strong><span className="assistant-online"><i/>Online</span></div><small>{plan}</small></div><div><button className="icon-button" aria-label="Histórico de conversas" disabled={busy} onClick={showHistory}><History size={20}/></button><button className="icon-button" aria-label="Nova conversa" disabled={busy} onClick={()=>{setMessages([]);setConversationId(undefined);setError(null);setFailedText(undefined);}}><Plus size={21}/></button></div></div><div className="message-scroll">{messages.length===0?<AssistantEmptyState role={role} onSelect={setValue}/>:<div className="messages">{messages.map(m=><AssistantMessage key={m.id} message={m}/>)}<button className="text-button" onClick={()=>navigate(`${base}/agenda`)}>Abrir agenda ↗</button></div>}{busy&&<div className="thinking" role="status">FIO está preparando sua resposta<span>•••</span></div>}<div ref={end}/></div><div className="composer-area">{error&&<AssistantErrorState error={error} onRetry={failedText&&!busy?()=>void send(failedText):undefined}/>}<AssistantComposer value={value} onChange={setValue} onSubmit={submit} busy={busy}/><p>A IA pode cometer erros. Confira informações antes de agir.</p></div>{history&&<Modal title="Suas conversas" onClose={()=>setHistory(null)}>{history.length===0?<p className="muted">Nenhuma conversa ainda.</p>:history.map(h=><button key={h.id} className="history-item" onClick={()=>openConversation(h.id)}>{h.title}</button>)}</Modal>}</div>;
}
