import {useEffect,useState} from 'react';
import type {WorkspaceProps} from '../pages/Workspace';
import {api} from '../lib/api';
export function PushSettings(p:WorkspaceProps){
 const [changes,setChanges]=useState(true),[reminders,setReminders]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[enabled,setEnabled]=useState(false),[config,setConfig]=useState<{configured:boolean;publicKey:string}|null>(null);
 useEffect(()=>{let alive=true;if(!p.demo)void api<{configured:boolean;publicKey:string}>('/push/config',p.data.shop.id).then(c=>{if(alive)setConfig(c);}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[p.demo,p.data.shop.id]);
 const supported='serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
 useEffect(()=>{let alive=true;if(supported&&!p.demo)void Promise.all([navigator.serviceWorker.getRegistration().then(r=>r?.pushManager.getSubscription()),api<{endpoint:string;enabled:boolean;changes:boolean;reminders:boolean}[]>('/push/preferences',p.data.shop.id)]).then(([s,rows])=>{if(!alive)return;const stored=rows.find(r=>r.endpoint===s?.endpoint);setEnabled(Boolean(stored?.enabled));if(stored){setChanges(stored.changes);setReminders(stored.reminders);}}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[supported,p.demo,p.data.shop.id]);
 async function enable(){setBusy(true);setMessage('');try{
  if(p.demo)throw Error('A demonstração não envia notificações.');
  if(!config?.configured)throw Error('As notificações ainda não foram configuradas pelo responsável pelo FIO.');
  const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Permissão não concedida. Você pode liberá-la nas configurações deste navegador.');
  const registration=await navigator.serviceWorker.ready;
  const key=Uint8Array.from(atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
  const subscription=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});
  const json=subscription.toJSON();await api('/push/devices',p.data.shop.id,{optIn:true,endpoint:subscription.endpoint,keys:json.keys,changes,reminders});setEnabled(true);setMessage('Preferências salvas para esta conta e barbearia neste dispositivo.');
 }catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function disable(){setBusy(true);try{const r=await navigator.serviceWorker.getRegistration(),s=await r?.pushManager.getSubscription();if(s)await api('/push/devices',p.data.shop.id,{endpoint:s.endpoint},'DELETE');setEnabled(false);setMessage('Notificações desativadas para esta conta e barbearia neste dispositivo.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="settings-card"><h2>Notificações neste dispositivo</h2><p>Receba avisos discretos sobre seus agendamentos mesmo com o FIO fechado. Nomes e detalhes não aparecem na tela bloqueada.</p><label className="check-row"><input type="checkbox" checked={changes} onChange={e=>setChanges(e.target.checked)}/>Confirmações, cancelamentos e remarcações</label><label className="check-row"><input type="checkbox" checked={reminders} onChange={e=>setReminders(e.target.checked)}/>Lembrete no dia anterior (até 24 horas antes)</label>{supported?<div className="modal-actions"><button className="primary" disabled={busy||!config?.configured} onClick={()=>void enable()}>{enabled?'Salvar e ativar preferências':'Ativar notificações'}</button>{enabled&&<button className="secondary" disabled={busy} onClick={()=>void disable()}>Desativar aqui</button>}</div>:<p>Este navegador não oferece Web Push. No iPhone/iPad com iOS 16.4 ou superior, adicione o FIO à Tela de Início e abra pelo ícone.</p>}{!config?.configured&&<p className="muted">Ativação disponível após a configuração de Web Push pelo responsável pelo FIO.</p>}<h3>Avisos recentes</h3>{p.data.notifications.length?p.data.notifications.map(n=><article key={n.id} className="schedule-block"><div><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('pt-BR')}</small></div><a className="secondary" href={p.base+'/agenda'+(n.appointment_id?'?appointment='+n.appointment_id:'')}>Abrir agenda</a></article>):<p>Nenhum aviso recente.</p>}<p className="muted">A entrega depende da conexão, das permissões e das configurações do sistema. Os avisos também ficam disponíveis no FIO.</p>{message&&<p role="status" className="notice">{message}</p>}</section>;
}

