import {useEffect,useState} from 'react';
import type {WorkspaceProps} from '../pages/Workspace';
import {api} from '../lib/api';
import {Field} from './ui';
type Hour={barber_id?:string;weekday:number;opens_at:string;closes_at:string};
type Block={id:string;barber_id:string;starts_at:string;ends_at:string};
type Snapshot={hours:Hour[];blocks:Block[];rules:{barber_id:string;service_id:string;enabled:boolean}[]};
export function StaffSchedule(p:WorkspaceProps){
 const team=p.data.team.filter(t=>t.active&&t.role==='BARBER');
 const [barber,setBarber]=useState(team[0]?.user_id??''),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[hours,setHours]=useState<Hour[]>([]),[disabled,setDisabled]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');
 async function load(){const next=p.demo?{hours:[],blocks:[],rules:[]}:await api<Snapshot>('/staff-schedule',p.data.shop.id);setSnapshot(next);return next;}
 useEffect(()=>{let alive=true;void (p.demo?Promise.resolve({hours:[],blocks:[],rules:[]}):api<Snapshot>('/staff-schedule',p.data.shop.id)).then(v=>{if(alive)setSnapshot(v);}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[p.demo,p.data.shop.id]);
 useEffect(()=>{if(snapshot){setHours(snapshot.hours.filter(h=>h.barber_id===barber).map(({weekday,opens_at,closes_at})=>({weekday,opens_at:opens_at.slice(0,5),closes_at:closes_at.slice(0,5)})));setDisabled(snapshot.rules.filter(r=>r.barber_id===barber&&!r.enabled).map(r=>r.service_id));}},[barber,snapshot]);
 async function save(){setBusy(true);setMessage('');try{if(p.demo)throw Error('Alteração indisponível na demonstração.');await api('/staff-schedule',p.data.shop.id,{barberId:barber,hours,disabledServices:disabled});await load();setMessage('Expediente e serviços salvos. Agendamentos existentes foram preservados.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function block(){setBusy(true);setMessage('');try{if(p.demo)throw Error('Alteração indisponível na demonstração.');await api('/staff-blocks',p.data.shop.id,{barberId:barber,startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString()});await load();setStart('');setEnd('');setMessage('Bloqueio adicionado. Confira os agendamentos existentes nesse intervalo.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);try{await api(`/staff-blocks/${id}`,p.data.shop.id,undefined,'DELETE');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="settings-card"><h2>Equipe, horários e serviços</h2><Field label="Profissional"><select value={barber} onChange={e=>setBarber(e.target.value)}>{team.map(t=><option key={t.user_id} value={t.user_id}>{t.display_name}</option>)}</select></Field><p>Sem faixas próprias, vale o expediente da barbearia. Ao adicionar faixas, apenas os dias e intervalos abaixo ficam disponíveis, sempre dentro do expediente da barbearia. Separe manhã e tarde para reservar uma pausa.</p><p className="muted">Fuso da agenda: {p.data.shop.timezone}. Alterações não cancelam horários já reservados.</p>{hours.map((h,i)=><div className="schedule-hour" key={i}><Field label="Dia"><select value={h.weekday} onChange={e=>setHours(v=>v.map((x,n)=>n===i?{...x,weekday:Number(e.target.value)}:x))}>{['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((d,n)=><option value={n} key={d}>{d}</option>)}</select></Field><Field label="Início"><input type="time" value={h.opens_at} onChange={e=>setHours(v=>v.map((x,n)=>n===i?{...x,opens_at:e.target.value}:x))}/></Field><Field label="Fim"><input type="time" value={h.closes_at} onChange={e=>setHours(v=>v.map((x,n)=>n===i?{...x,closes_at:e.target.value}:x))}/></Field><button className="secondary" aria-label={`Remover faixa ${i+1}`} onClick={()=>setHours(v=>v.filter((_,n)=>n!==i))}>Remover</button></div>)}<button className="secondary" disabled={!barber||hours.length>=28} onClick={()=>setHours(v=>[...v,{weekday:1,opens_at:'09:00',closes_at:'18:00'}])}>Adicionar faixa</button><h3>Serviços realizados</h3>{p.data.services.filter(s=>s.active).map(s=><label className="check-row" key={s.id}><input type="checkbox" checked={!disabled.includes(s.id)} onChange={e=>setDisabled(v=>e.target.checked?v.filter(id=>id!==s.id):[...v,s.id])}/>{s.name}</label>)}<button className="primary" disabled={busy||!barber||!snapshot||hours.some(h=>h.closes_at<=h.opens_at)} onClick={()=>void save()}>Salvar expediente e serviços</button><hr/><h3>Ausências e bloqueios</h3><p>Os campos abaixo usam o fuso deste dispositivo ({Intl.DateTimeFormat().resolvedOptions().timeZone}); o horário salvo é convertido para a agenda.</p><Field label="Bloqueio começa"><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Bloqueio termina"><input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></Field><button className="secondary" disabled={busy||!start||!end||end<=start||!barber} onClick={()=>void block()}>Adicionar bloqueio</button>{snapshot?.blocks.filter(b=>b.barber_id===barber).map(b=><div className="schedule-block" key={b.id}><span>{new Date(b.starts_at).toLocaleString('pt-BR',{timeZone:p.data.shop.timezone})} — {new Date(b.ends_at).toLocaleString('pt-BR',{timeZone:p.data.shop.timezone})}</span><button className="secondary" disabled={busy} onClick={()=>void remove(b.id)}>Remover bloqueio</button></div>)}{message&&<p className="notice" role="status">{message}</p>}</section>;
}

